### ISSUE TITLE
I as a user want to see an onboarding screen of the Quiz which explains me what I can do with the application

### ISSUE THREAD

**Issue by md-weber** [md-weber/envubi#1]
## Tasks

- [x] Onboarding with three different screens, that can have a headline and a body text
- [x] Translatable body and headline texts also the buttons have to be translatable
- [x] For each text he wants to see an image
- [x] The images and the text should be swipeable while the login and register button should in a fixed position
- [x] Add the login and register button

**Comment by md-weber** [comment]
### **Update 22.04.22**

~Callback on click of the dots to make navigate to the specific tab view~ 
~Skip to the correct page (1 - 3, 3 - 1)~
Removed from current task because it is not really user friendly and is more an indication.

- [x] Make it more smooth between the different screens and align the dots to it 

### Hint 
Use `controller.offset` to get the information between the different views.
